language: python
python:
  - 2.7

install:
  - sudo apt-get install libboost-python-dev libboost-thread-dev libboost-system-dev
  - sudo apt-get install systemtap-sdt-dev
  - git clone https://github.com/damoti/python-v8.git
  - pip install -e python-v8
  - pip install -e .
  - pip install -r requirements.pip

script:
    - py.test --cov jscov8 -s

after_success:
  - coveralls
